### ISSUE TITLE
vyasm fails in folders with spaces in it

### ISSUE THREAD

**Issue by doskabouter** [yasm/yasm#158]
In current vsyasm.targets this line:
`CommandLineTemplate="$(MSBuildThisFileDirectory)\vsyasm.exe -Xvc -f %(YASM.Platform) [AllOptions] [AdditionalOptions] [Inputs]"`

should be cchanged to:
`CommandLineTemplate="&quot;$(MSBuildThisFileDirectory)\vsyasm.exe&quot; -Xvc -f %(YASM.Platform) [AllOptions] [AdditionalOptions] [Inputs]"`

**Comment by BrianGladman** [comment]
I cannot find a vsyasm.targets file in this repository that includes the line you refer to above . Can you please indicate where this file is located?

**Comment by doskabouter** [comment]
don't know where in the source this is, I found it when installing the nuget package (in "Packages\vsyasm.1.3.0.3\build\vsyasm.targets")

**Comment by BrianGladman** [comment]
Since the file you reference is a part of the nuget package but is not present in the YASM repository here, it seems that the nuget package is out-of-date.    I suggest that you report this to the author/maintainer of the nuget package.  Alternatively you could build YASM from this repository and install it manually.

**Comment by doskabouter** [comment]
Well, only link in nuget package (https://www.nuget.org/packages/vsyasm/1.3.0.3) is to http://yasm.tortall.net/ and that linked to this repo so I assumed this was the correct place to create the issue. Can you point me to the correct place for creating issues with that nuget package if this is indeed not the right place?

**Comment by BrianGladman** [comment]
This would be the right place to report the issue if the file in question was a part of YASM as it is now, but it isn't (as far as I can see).   Oddly the command line template for YASM now appears in the *.props file, not the *.targets file, so the nuget package may have diverged from YASM.   

The owner of the nuget package is at: https://www.nuget.org/profiles/michalw

Although the YASM repository is up to date, the links on the YASM web page are not and this could be where the issue lies.   You would need to raise this with Peter Johnson, who maintains the web site.

**Comment by doskabouter** [comment]
Do you happen to have some contact info for him? Nuget won't show me without an accound

**Comment by BrianGladman** [comment]
I'm afraid not as I have never used (or been involved) in nuget packaging.

**Comment by doskabouter** [comment]
ok thanks anyway
