### ISSUE TITLE
bug? $

### ISSUE THREAD

**Issue by icyfox168168** [yasm/yasm#187]
yasm.s:9: error: expression missing after `$'
yasm.s:22: error: directive `.global' requires an argument
yasm.s:23: error: label or instruction expected at start of line

s to o

	.global xxxxf
xxxxf:
	pushq %rbp
	movq %rsp, %rbp
	subq $16, %rsp
.LB1:
#instruction start "1 <- temporary":
#instruction start "1 = constant":
	movabsq $a, %rdi
	leaq -4(%rbp), %rsi
	movl 0(%rdi), %eax
	movl %eax, 0(%rsi)
#instruction start "clear stack bucket 1":
# EXIT IS OF TYPE : 1
	movq -4(%rbp), %rax
	leave
	ret
.LB2:
# EXIT IS OF TYPE : 0
	ud2
	.section .data
	.global a
a:
	.zero 4
	.section .text

**Comment by arizvisa** [comment]
please triple-backtick the code in your report, it makes it significantly easier to read.  anyways, I tried the following and it seems to work for me.

i'm testing with the following version:
```
$ yasm --version
yasm 1.3.0
Compiled on Jan 28 2021.
Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
```

here's what i was able to decode from your markdown-mangled example:
```
$ cat >| fuck.s 
.global xxxxf
xxxxf:
pushq %rbp
movq %rsp, %rbp
subq $16, %rsp
.LB1:
#instruction start "1 <- temporary":
#instruction start "1 = constant":
movabsq $a, %rdi
leaq -4(%rbp), %rsi
movl 0(%rdi), %eax
movl %eax, 0(%rsi)
#instruction start "clear stack bucket 1":
#EXIT IS OF TYPE : 1
movq -4(%rbp), %rax
leave
ret
.LB2:
#EXIT IS OF TYPE : 0
ud2
.section .data
.global a
a:
.zero 4
.section .text
$ yasm -felf64 -pgas -o fuck.o fuck.s && echo $?
0
```

as you can see, it seems to assemble properly. it also seems to emit:
```
$ objdump -d fuck.o

fuck.o:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <xxxxf>:
   0:	55                   	push   %rbp
   1:	48 89 e5             	mov    %rsp,%rbp
   4:	48 83 ec 10          	sub    $0x10,%rsp
   8:	48 bf 00 00 00 00 00 	movabs $0x0,%rdi
   f:	00 00 00 
  12:	48 8d 75 fc          	lea    -0x4(%rbp),%rsi
  16:	8b 07                	mov    (%rdi),%eax
  18:	89 06                	mov    %eax,(%rsi)
  1a:	48 8b 45 fc          	mov    -0x4(%rbp),%rax
  1e:	c9                   	leaveq 
  1f:	c3                   	retq   
  20:	0f 0b                	ud2    
```

it would be helpful to output the version of yasm you're using and what platform you're running on. (although, i'm pretty sure you're using windows).

also...for the sake of making it easier for the maintainers of yasm, can you modify the title of this issue to be more clear about what you feel the bug is? maybe the error that's being emitted would be more useful than just "bug? $".
